### ISSUE TITLE
latest 1.10.2 java crash

### ISSUE THREAD

**Issue by mightydanp** [Glitchfiend/ToughAsNails#117]
[04:06:37] [Client thread/ERROR] [ToughAsNails Transformer]: Unexpected hash e444f6b905ca7b5a856b939a07b1568d detected for class EntityRenderer. Crashes or bugs may occur!
[04:06:38] [Client thread/WARN]: Skipping bad option: lastServer:
[04:06:41] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1121) ~[bnz.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) ~[bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: bxl
    at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224) ~[Restriction.class:?]
    at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498) ~[VersionRange.class:?]
    at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106) ~[GuiModsMissing.class:?]
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) ~[ForgeHooksClient.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) ~[bnz.class:?]
    ... 9 more
[04:06:41] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

**Comment by ghost** [comment]
Getting the same issue here, subscribed for updates, this plugin looks brilliant!

**Comment by matshou** [comment]
How did you guys even get it running on 1.10.2? It's not compatible, at least from what I've seen after cloning the repo.

**Comment by ghost** [comment]
That explains the problem then haha, Let's hope for an update!

**Comment by matshou** [comment]
It's been a couple of months already since the last update, hope it happens.

**Comment by ghost** [comment]
Fingers crossed, I need to learn java!

**Comment by Forstride** [comment]
1.9.4 mods are naturally forwards compatible with 1.10.2.  As for this issue, and every other one on here, it's up to Adubbz to fix them, and I have no idea what his current situation is like, so...Yeah...

**Comment by matshou** [comment]
I would very happy to help you solve some issues here if I could only find a compatible forge version. Forge version "1.10.2-12.18.1.2011" is not compatible with the "TAN 1.9.4.-1.0.0" branch code. What was the last forge version the project was compatible with?

**Comment by ghost** [comment]
Pass @yooksi I'm using spigot for this example... :8ball:

**Comment by hanleybrand** [comment]
I am able to get it to work with 1.10.2 and Forge 12.18.2.2107, but some mods conflict (in my case it was localized weather and storms (weather2-1.10.2-2.3.15.jar)

**Comment by Adubbz** [comment]
This sounds like an incompatibility with Spigot's modifications to Vanilla classes. Similar to Optifine, this is not something we support.  Additionally, given the whole Bukkit DMCA fiasco making it hard to access the source, this is not something that is likely to get fixed, at least not by myself. If someone wishes to look into this they're certainly welcome to, however for the time being I'm closing this issue.
