### ISSUE TITLE
Error with "Caverns" mod

### ISSUE THREAD

**Issue by Kisonu** [Glitchfiend/ToughAsNails#137]
I've updated forge and all my mods to the latest versions but your mod is giving the below crash report when installed with "Caverns"

(Sorry that its not in a spoiler, i dont know how...)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TANLoadingPlugin (ToughAsNails-1.11-2.0.1.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 11/19/16 8:55 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tough As Nails (toughasnails)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.EntityRegistry.registerModEntity(Ljava/lang/Class;Ljava/lang/String;ILjava/lang/Object;IIZ)V
	at toughasnails.init.ModEntities.registerTANEntity(ModEntities.java:45)
	at toughasnails.init.ModEntities.init(ModEntities.java:34)
	at toughasnails.core.ToughAsNails.preInit(ToughAsNails.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:263)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:438)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:350)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 64873736 bytes (61 MB) / 322961408 bytes (308 MB) up to 975175680 bytes (930 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx930M -XX:+UseG1GC -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=10 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=3 -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.35 Powered by Forge 13.19.0.2153 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11-13.19.0.2153.jar) 
	UCH	forge{13.19.0.2153} [Minecraft Forge] (forge-1.11-13.19.0.2153.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCH	biomeheighttweaker{1.11-0.6} [Biome Height Tweaker] (biomeheighttweaker-1.11-0.6.jar) 
	UCH	biomesoplenty{6.0.0.2106} [Biomes O' Plenty] (BiomesOPlenty-1.11-6.0.0.2106-universal.jar) 
	UCH	cavern{1.6.0} [Cavern] (Cavern_1.11-v1.6.0-alpha2.jar) 
	UCH	clienttweaks{2.1.2} [Client Tweaks] (ClientTweaks_1.11-2.1.2.jar) 
	UCH	compasscoords{1.11-3.2.4} [Compass Co-ords] (CompassCoords-1.11-3.2.4.jar) 
	UCH	craftingcraft{5.1.1} [CraftingCraft] (CraftingCraft_1.11-5.1.1.jar) 
	UCH	craftingtweaks{7.1.1} [Crafting Tweaks] (CraftingTweaks_1.11-7.1.1.jar) 
	UCH	creativeparadise{1.0.0} [Creative Paradise] (creativeparadise-1.0.0.jar) 
	UCH	floricraft{beta-1.1.6} [Floricraft] (Floricraft-1.11-beta1.1.6.jar) 
	UCH	flourpower{1.11-0.0.3} [Flour Power] (FlourPower-1.11-0.0.3.jar) 
	UCH	gravestone{1.6.0} [Gravestone] (GraveStone Mod 1.6.jar) 
	UCH	infinitefluids{1.1.0} [InfiniteFluids] (infinitefluids-1.11-1.1.0.jar) 
	UCH	jei{4.0.1.193} [Just Enough Items] (jei_1.11-4.0.1.193.jar) 
	UCH	justenoughbuttons{1.11-1.0} [Just Enough Buttons] (justenoughbuttons-1.11-1.0.jar) 
	UCH	jeresources{0.6.0.91} [Just Enough Resources] (JustEnoughResources-1.11-0.6.0.91.jar) 
	UCH	lteleporters{1.1.4} [Lemon's Simple Teleporters] (MC 1.11 Lemon's Simple Teleporters 1.1.4.jar) 
	UCH	mysticalagriculture{1.3.4} [Mystical Agriculture] (mysticalagriculture[1.11]-1.3.4.jar) 
	UCH	oreexcavation{1.3.37} [OreExcavation] (OreExcavation-1.3.37.jar) 
	UCH	rockcandy{1.10.2-1.1} [Rock Candy] (rockcandy-1.11-0.1.jar) 
	UCH	thut_wearables{2.1.1} [Thut's Wearables] (thut_wearables-2.1.1.b.jar) 
	UCH	thutcore{4.0.1} [ThutCore] (thutcore-4.0.1.h.jar) 
	UCH	thutessentials{1.6.0} [Thut Essentials] (thutessentials-1.6.0.jar) 
	UCH	thuttech{5.0.0} [Thut's Tech] (thuttech-5.0.0.b.jar) 
	UCE	toughasnails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.11-2.0.1.jar) 
	Loaded coremods (and transformers): 
TANLoadingPlugin (ToughAsNails-1.11-2.0.1.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics'

**Comment by Adubbz** [comment]
Fixed in 2.0.2. This was an issue with Forge, not Caverns.
