### ISSUE TITLE
[1.11] TaN with forge not loading

### ISSUE THREAD

**Issue by Makomea** [Glitchfiend/ToughAsNails#146]
Hello! To give you some background to this issue, I started a thread on the BoP issues forum about adding Llama's to other BoP biomes. Adubbz fixed that up pretty quick and snazzy like ^_^ The problem started here though, after I installed the updated BoP mod, minecraft said that "Biomes o Plenty is missing required files to work" and it provided a new version of Forge to download.  I went to the forge website and downloaded the latest one they have available and installed it just fine. I loaded minecraft but it crashed before getting to the title screen. The MC client provided an error report stating it was Tough as Nails that caused the issue. I removed it, reloaded the game and everything worked fine including some other misc. mods. I replaced TaN back to the mod folder and it crashed again providing an identical error report.  I will now provide that log to you. I am unsure as to the best way to paste it as some people like it in a "spoiler" button hidden away... I don't know how to do that so I apologize if this is a messy cut and paste for the log. I hope it helps and I look forward to playing with my favorite survival mod!  =^_^= Thank you guys for creating and sharing TaN.

==EDIT==: The latest version Tough as Nails will work with Forge is v13.19.0.2159.  Any forge version after that and it doesn't work at all.  All of the Biomes o Plenty for 1.11 require later versions of forge to operate so as it stands both mods cannot work with each other. Also, the icons in Tough as nails are blacked out. You cannot see what status you are affected with when it comes to being thirsty or other special status's that show up. You can see the health, hunger, and temperature icons just fine though.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.11-1.2.0.0.b79.jar)
  TANLoadingPlugin (ToughAsNails-1.11-2.0.2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 12/3/16 2:10 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tough As Nails (toughasnails)
Caused by: java.lang.NoSuchFieldError: customCraftingMaterial
	at toughasnails.init.ModItems.registerItems(ModItems.java:76)
	at toughasnails.init.ModItems.init(ModItems.java:64)
	at toughasnails.core.ToughAsNails.preInit(ToughAsNails.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:615)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:264)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:438)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:350)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1400966216 bytes (1336 MB) / 2010644480 bytes (1917 MB) up to 2010644480 bytes (1917 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -Xms2G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.35 Powered by Forge 13.19.0.2178 Optifine OptiFine_1.11_HD_U_B2 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11-13.19.0.2178.jar) 
	UCH	forge{13.19.0.2178} [Minecraft Forge] (forge-1.11-13.19.0.2178.jar) 
	UCH	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11-1.2.0.0.b79.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCH	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11-1.2.0.0.b79.jar) 
	UCH	aromabackup{1.0} [AromaBackup] (AromaBackup-1.11-2.1.0.0.b63.jar) 
	UCH	aromabackuprecovery{1.0} [AromaBackupRecovery] (AromaBackup-1.11-2.1.0.0.b63.jar) 
	UCH	bettersprinting{1.1.8} [Better Sprinting] (BetterSprinting  MC-1.11  v1.1.8.jar) 
	UCH	biomesoplenty{6.0.0.2120} [Biomes O' Plenty] (BiomesOPlenty-1.11-6.0.0.2120-universal.jar) 
	UCH	clienttweaks{2.1.2} [Client Tweaks] (ClientTweaks_1.11-2.1.2.jar) 
	UCH	commandkeybindings{7.0.0} [Command Keybindings] (CommandKeybindings-Forge-7.0.0.jar) 
	UCH	endercompass{1.2.5.1} [Ender Compass] (EnderCompass-1.11-1.2.5.1.jar) 
	UCH	endercrop{1.11-1.3.3} [Ender Crop] (endercrop-1.11-1.3.3.jar) 
	UCH	gravestone{1.6.0} [Gravestone] (GraveStone Mod 1.6.jar) 
	UCH	itemscroller{0.7.2} [Item Scroller] (itemscroller-1.11.0-0.7.2.jar) 
	UCH	jei{4.0.2.194} [Just Enough Items] (jei_1.11-4.0.2.194.jar) 
	UCH	llor{1.1.1-mc[1.9-1.11]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar) 
	UCH	overlord{2.0.0} [Overlord] (Overlord-2.0.0.jar) 
	UCE	toughasnails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.11-2.0.2.jar) 
	UCH	vanillamagic{1.11-0.21.0.2} [Vanilla Magic] (vanillamagic-1.11-0.21.0.2.jar) 
	UCH	waddles{0.5.1} [Waddles] (Waddles-1.11-0.5.1.jar) 
	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.11-1.2.0.0.b79.jar)
  
TANLoadingPlugin (ToughAsNails-1.11-2.0.2.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.4.13283 Compatibility Profile Context 14.501.1003.0' Renderer: 'AMD Radeon HD 5700 Series'
	OptiFine Version: OptiFine_1.11_HD_U_B2
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.13283 Compatibility Profile Context 14.501.1003.0
	OpenGlRenderer: AMD Radeon HD 5700 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Adubbz** [comment]
Fixed in https://github.com/Glitchfiend/ToughAsNails/commit/73bd06a858b7b188bba9b906f8e6a734b0b95a33

**Comment by Makomea** [comment]
Thank you so much Adubbz!  You are the man, if I could send you a cookie I would. ^_*
