### ISSUE TITLE
Game crash for 1.12-3.0.0.52 on load with forge 14.21.1.2387

### ISSUE THREAD

**Issue by TheSayyadin** [Glitchfiend/ToughAsNails#285]
involved files:
forge-1.12-14.21.1.2387.jar
toughAsNails-1.12-3.0.0.52-universal.jar

The game crashed when I was trying to make a small pack to play and I could not start as it crashed right away. So I removed all mods except for TAN and it still crashes without any other mods present.

This might be related to or a duplicate of #274 

Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer toughasnails.asm.transformer.CropDecayTransformer@6738e8b2 from coremod TANLoadingPlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 44 more
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at toughasnails.asm.transformer.CropDecayTransformer.transform(CropDecayTransformer.java:46)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 46 more

**Comment by Shadows-of-Fire** [comment]
TaN isnt updated for any forge past 2347 yet, keep an eye on #287 or watch commits.  This isn't the usual error, but its probably caused by the same thing.

**Comment by Adubbz** [comment]
Fixed after merging Shadows' PR.
