### ISSUE TITLE
Tempregulator not initilized correctly

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/ToughAsNails#306]
Hello,

everytime I started my forever stranded server, I get this error message. It seems not to influence the correct running, of my server, but its just an error.

11:05:42] [Server thread/ERROR] [FML/]: A TileEntity tanaddons:tempregulator(p455w0rd.tanaddons.tiles.TileTempRegulator) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
        at p455w0rd.tanaddons.tiles.TileTempRegulator.func_145839_a(TileTempRegulator.java:164) ~[TileTempRegulator.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123) [aqk.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) [atj.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115) [lr.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86) [lr.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:132) [lr.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:298) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:268) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) [ld.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

Regards,
Karsten

**Comment by Adubbz** [comment]
That belongs to tanaddons, not TaN.

**Comment by ghost** [comment]
Ok thanks, will report there. 
But further, how to understand that errors:

[11:04:16] [main/ERROR] [ToughAsNails Transformer/]: Unexpected hash e601eef309ce9cf3ecb5f70ac0e31516 detected for class World. Crashes or bugs may occur!

[11:04:18] [main/ERROR] [ToughAsNails Transformer/]: Unexpected hash 20f2d689046ef2bce53aff9618487c56 detected for class BlockCrops. Crashes or bugs may occur!

**Comment by Adubbz** [comment]
That means that new versions of Forge or some other mod has modified those classes from what is expected by TaN. It's possible that it may cause issues, but it's also possible that it doesn't, we don't know until it happens
