### ISSUE TITLE
(1.12)minecraft crash ! help

### ISSUE THREAD

**Issue by 3778864814** [Glitchfiend/ToughAsNails#311]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TANLoadingPlugin (ToughAsNails-1.12.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 7/23/17 9:46 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Treecapitator (treecapitator)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/IForgeRegistryEntry
	at bspkrs.treecapitator.registry.ToolRegistry.initVanillaItemLists(ToolRegistry.java:65)
	at bspkrs.treecapitator.registry.ToolRegistry.<init>(ToolRegistry.java:46)
	at bspkrs.treecapitator.registry.ToolRegistry.instance(ToolRegistry.java:26)
	at bspkrs.treecapitator.registry.ThirdPartyModConfig.<init>(ThirdPartyModConfig.java:45)
	at bspkrs.treecapitator.registry.ThirdPartyModConfig.<init>(ThirdPartyModConfig.java:59)
	at bspkrs.treecapitator.registry.ModConfigRegistry.initDefaultModConfigs(ModConfigRegistry.java:245)
	at bspkrs.treecapitator.registry.ModConfigRegistry.<init>(ModConfigRegistry.java:47)
	at bspkrs.treecapitator.registry.ModConfigRegistry.instance(ModConfigRegistry.java:35)
	at bspkrs.treecapitator.config.TCConfigHandler.syncConfig(TCConfigHandler.java:108)
	at bspkrs.treecapitator.config.TCConfigHandler.<init>(TCConfigHandler.java:71)
	at bspkrs.treecapitator.config.TCConfigHandler.setInstance(TCConfigHandler.java:33)
	at bspkrs.treecapitator.TreecapitatorMod.preInit(TreecapitatorMod.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:614)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.registry.IForgeRegistryEntry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 52 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer toughasnails.asm.transformer.CropDecayTransformer@104cfb24 from coremod TANLoadingPlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 54 more
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at toughasnails.asm.transformer.CropDecayTransformer.transform(CropDecayTransformer.java:46)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 56 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1706614648 bytes (1627 MB) / 2028994560 bytes (1935 MB) up to 2028994560 bytes (1935 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M -Xms2048M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2420 Optifine OptiFine_1.12_HD_U_C4 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2420.jar) 
	UCH	forge{14.21.1.2420} [Minecraft Forge] (forge-1.12-14.21.1.2420.jar) 
	UCH	durabilityshow{5.0.0} [Durability Show] (Durability Show-1.12-5.0.0.jar) 
	UCH	ic2{2.8.4-ex112} [IndustrialCraft 2] (industrialcraft-2-2.8.4-ex112.jar) 
	UCH	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCH	jei{4.7.1.69} [Just Enough Items] (jei_1.12-4.7.1.69.jar) 
	UCH	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCH	neat{1.4-15} [Neat] (Neat 1.4-15.jar) 
	UCH	oretweaker{1.0.2-1.12.0} [Ore Tweaker] (Ore-Tweaker-Mod-1.12.jar) 
	UCH	toughasnails{3.0.0.59} [Tough As Nails] (ToughAsNails-1.12.jar) 
	UCH	bspkrscore{at_0.9} [bspkrsCore] (Treecapitator-1.12-at_0.9.jar) 
	UCE	treecapitator{at_0.9} [Treecapitator] (Treecapitator-1.12-at_0.9.jar) 
	UCH	veinminer{0.36.0} [Vein Miner] (VeinMiner-1.11-0.36.0.621+8499b73.jar) 
	UCH	veinminermodsupport{0.36.0} [Mod Support] (VeinMiner-1.11-0.36.0.621+8499b73.jar) 
	Loaded coremods (and transformers): 
TANLoadingPlugin (ToughAsNails-1.12.jar)
  toughasnails.asm.transformer.CropDecayTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.4242' Renderer: 'Intel(R) HD Graphics'
	OptiFine Version: OptiFine_1.12_HD_U_C4
	Render Distance Chunks: 3
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.2.0 - Build 10.18.10.4242
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by rckymtnrfc** [comment]
This error is from Treecapitator, not TAN.
