### ISSUE TITLE
[1.11.2]java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [Glitchfiend/ToughAsNails#366]
Forge build 2510

```
Description: Exception in server tick loop

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/world/World.func_175727_C(Lnet/minecraft/util/math/BlockPos;)Z @53: ifeq
  Reason:
    Type 'toughasnails/api/season/Season' (current frame, stack[3]) is not assignable to integer
  Current Frame:
    bci: @53
    flags: { }
    locals: { 'net/minecraft/world/World', 'net/minecraft/util/math/BlockPos', 'toughasnails/api/season/Season' }
    stack: { 'net/minecraft/world/World', 'net/minecraft/util/math/BlockPos', 'toughasnails/api/season/Season', 'toughasnails/api/season/Season' }
  Bytecode:
    0x0000000: 2ab6 09f0 9a00 0503 ac2a 2bb6 02fa 9a00
    0x0000010: 0503 ac2a 2bb6 09f2 b601 892b b601 89a4
    0x0000020: 0005 03ac 2ab8 0803 b908 0901 00b6 080f
    0x0000030: 4d2a 2b2c 5999 0009 572a 2bb8 09f5 b809
    0x0000040: f9ac                                   
  Stackmap Table:
    same_frame(@9)
    same_frame(@19)
    same_frame(@36)

	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:85)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:120)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
```

**Comment by Secretname2009** [comment]
I am getting this error aswell in 1.11.2, gonna attach crashlog since the one above doesnt include mod Version or anything.
[crash-2017-11-16_10.59.45-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/1478123/crash-2017-11-16_10.59.45-client.txt)

Forge Version: 13.20.1.2530
TAN Version: 2.1.0.65
Mod list is in the Crashlog

**Comment by Adubbz** [comment]
This is an issue with random things, remove it and it should work fine.
