### ISSUE TITLE
Crash on WorldLoad\Create with DynamicSurroundings

### ISSUE THREAD

**Issue by GordonHollow** [Glitchfiend/ToughAsNails#477]
ToughAsNails-1.12.2-3.1.0.97
On .96 version all works correctly with DynSurroundings, but .96 don't work with SereneSeasons.
Maybe name conflict with DynSurround?

```
Unexpected error

java.lang.NoClassDefFoundError: toughasnails/api/season/SeasonHelper
	at org.blockartistry.DynSurround.registry.season.SeasonInfoToughAsNails.getSeasonType(SeasonInfoToughAsNails.java:56)
	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler$EnvironState.tick(EnvironStateHandler.java:146)
	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler$EnvironState.access$000(EnvironStateHandler.java:68)
	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler.process(EnvironStateHandler.java:401)
	at org.blockartistry.DynSurround.client.handlers.EffectManager.onTick(EffectManager.java:173)
	at org.blockartistry.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:183)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_397_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: toughasnails.api.season.SeasonHelper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 20 more
Caused by: java.lang.NullPointerException

```

**Comment by Adubbz** [comment]
Dynamic Surroundings will need to be updated to account for the move of seasons from TaN to Serene Seasons. Not really much we can do here.

**Comment by GordonHollow** [comment]
Ok, then i just re-open this issue on DynSurround github tracker
