### ISSUE TITLE
1.12.2 crash when loading game

### ISSUE THREAD

**Issue by missycud** [Glitchfiend/ToughAsNails#478]
So I don't know whether this issue is to do with my minecraft or the mod, but I'll say it anyway.
When I run minecraft, it comes up with the mojang screen as usual but when it gets to a certain part it crashes. I checked the crash report and I don't understand it whatsoever (this is my first time with an issue with mods). 
Here's my crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 4/13/18 12:36 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:522)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.EntityRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer toughasnails.asm.transformer.EntityRendererTransformer@5a311acd from coremod TANLoadingPlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 11 more
Caused by: java.lang.RuntimeException: An error occurred transforming EntityRenderer. Applied transformations: [c (F)V]
	at toughasnails.asm.transformer.EntityRendererTransformer.transformEntityRenderer(EntityRendererTransformer.java:86)
	at toughasnails.asm.transformer.EntityRendererTransformer.transform(EntityRendererTransformer.java:39)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:522)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 157462968 bytes (150 MB) / 385875968 bytes (368 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2654 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version      | Source                        | Signature                                |
	|:----- |:---------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCH   | minecraft  | 1.12.2       | minecraft.jar                 | None                                     |
	| UCH   | mcp        | 9.42         | minecraft.jar                 | None                                     |
	| UCH   | FML        | 8.0.99.99    | forge-1.12.2-14.23.2.2654.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge      | 14.23.2.2654 | forge-1.12.2-14.23.2.2654.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | lostcities | 2.0.5        | lostcities-1.12-2.0.5.jar     | None                                     |

	Loaded coremods (and transformers): 
TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 560 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.2.2654
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 560 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz

**Comment by Forstride** [comment]
You're trying to use a version of the mod for Minecraft 1.9.4 on 1.12.2...
