### ISSUE TITLE
[1.12.2] Incompatibility with DynamicSurroundings

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [Glitchfiend/ToughAsNails#488]
I wanted to create an new world but the game freezes
Iam using the newes ToughAsNails and season mod along with many other mods...

<details>
  <summary>Click to expand</summary>

```
  [09:33:42] [Server thread/ERROR]: ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190)
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2211_WorldEventHandler_onUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:381)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:786)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4153)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441)
	at journeymap.client.data.PlayerData.load(PlayerData.java:86)
	at journeymap.client.data.PlayerData.load(PlayerData.java:30)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 15 more
```
</details>
<details>
  <summary>Click to expand</summary>

```
[09:34:19] [main/INFO]: Creating Tough as Nails SeasonInfo for dimension overworld
[09:34:19] [main/ERROR]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ClientTickEvent@3444b6b4:
java.lang.NoClassDefFoundError: toughasnails/api/season/SeasonHelper
	at org.blockartistry.DynSurround.registry.season.SeasonInfoToughAsNails.getSeasonType(SeasonInfoToughAsNails.java:56) ~[SeasonInfoToughAsNails.class:?]
	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler$EnvironState.tick(EnvironStateHandler.java:146) ~[EnvironStateHandler$EnvironState.class:?]
	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler$EnvironState.access$000(EnvironStateHandler.java:68) ~[EnvironStateHandler$EnvironState.class:?]
	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler.process(EnvironStateHandler.java:401) ~[EnvironStateHandler.class:?]
	at org.blockartistry.DynSurround.client.handlers.EffectManager.onTick(EffectManager.java:173) ~[EffectManager.class:?]
	at org.blockartistry.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:183) ~[EffectManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_196_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: toughasnails.api.season.SeasonHelper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 20 more
Caused by: java.lang.NullPointerException
[09:34:19] [main/ERROR]: Index: 10 Listeners:
[09:34:19] [main/ERROR]: 0: HIGHEST
[09:34:19] [main/ERROR]: 1: ASM: class org.blockartistry.DynSurround.client.ClientChunkCache clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 2: ASM: net.fokson.embassy.event.ClientEvents@1faeaecb OnTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 3: ASM: net.fokson.actualmusic.event.ClientEvents@1fd490cc OnTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 4: ASM: net.fokson.embassy.event.ClientEvents@dda2e73 OnTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 5: ASM: DiagnosticHandler{name=Diagnostics} tickStart(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 6: NORMAL
[09:34:19] [main/ERROR]: 7: ASM: class crazypants.enderio.base.TileEntityEio onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 8: ASM: class crazypants.enderio.base.handler.darksteel.DarkSteelController onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 9: ASM: class mcp.mobius.waila.overlay.WailaTickHandler tickClient(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 10: ASM: class org.blockartistry.DynSurround.client.handlers.EffectManager clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 11: ASM: com.minecolonies.coremod.event.FMLEventHandler@43f35683 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 12: ASM: class minecrafttransportsimulator.systems.ClientEventSystem on(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 13: ASM: it.zerono.mods.zerocore.internal.common.MultiblockEventHandler@5fe31628 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 14: ASM: net.minecraftforge.common.ForgeInternalHandler@490333e5 checkSettings(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 15: ASM: cofh.core.proxy.EventHandlerClient@36b9cdb2 handleClientTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 16: ASM: cofh.core.render.ShaderHelper@431a4b12 clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 17: ASM: vazkii.quark.client.feature.AutoJumpHotkey@3b394d16 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 18: ASM: vazkii.quark.client.feature.UsageTicker@44250fcb clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 19: ASM: vazkii.quark.management.feature.StoreToChests@609325e4 update(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 20: ASM: vazkii.quark.management.feature.ChangeHotbarKeybind@3a2a75fc onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 21: ASM: vazkii.quark.misc.feature.ExtraPotions@23185c7f clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 22: ASM: class vazkii.arl.util.ClientTicker clientTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 23: ASM: ic2.core.TickHandler@7219ed0 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 24: ASM: crazypants.enderio.base.teleport.TravelController@6fa05f85 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 25: ASM: crazypants.enderio.base.item.darksteel.upgrade.sound.SoundDetector@623a94f2 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 26: ASM: lumien.bloodmoon.client.ClientBloodmoonHandler@6c9d90b6 clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 27: ASM: codechicken.lib.render.CCRenderEventHandler@714b6311 clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 28: ASM: com.brandon3055.brandonscore.client.particle.BCEffectHandler@15434168 clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 29: ASM: com.brandon3055.brandonscore.client.BCClientEventHandler@5a2f0f87 tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 30: ASM: com.brandon3055.brandonscore.client.ProcessHandlerClient@2c2b49c0 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 31: ASM: mod.chiselsandbits.core.ClientSide@383635ca interaction(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 32: ASM: dan200.computality.client.proxy.CCTurtleProxyClient$ForgeHandlers@199f716a onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 33: ASM: toughasnails.handler.temperature.TemperatureOverlayHandler@408d3183 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 34: ASM: toughasnails.handler.thirst.ThirstOverlayHandler@26f2fbd1 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 35: ASM: forestry.greenhouse.multiblock.blocks.ChunkEvents@6fe406be onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 36: ASM: extendedrenderer.EventHandler@5fc5761d tickClient(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 37: ASM: flaxbeard.cyberware.common.item.ItemCybereyeUpgrade@2ed1951a tickStart(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 38: ASM: flaxbeard.cyberware.common.item.VanillaWares$SpiderEyeWare@7f2aa317 handleSpiderVision(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 39: ASM: INSTANCE onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 40: ASM: com.brandon3055.draconicevolution.lib.DEImageHandler@7f0818f tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 41: ASM: class org.blockartistry.DynSurround.client.sound.BackgroundMute clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 42: ASM: me.ichun.mods.ichunutil.client.core.event.EventHandlerClient@12963518 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 43: ASM: class com.feed_the_beast.ftblib.client.FTBLibClientEventHandler onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 44: ASM: codechicken.enderstorage.network.TankSynchroniser@38a5af03 tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 45: ASM: com.rwtema.extrautils2.items.DemonicIngotHandler@5f90712 run(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 46: ASM: com.rwtema.extrautils2.keyhandler.KeyAlt@226c9009 onPress(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 47: ASM: com.rwtema.extrautils2.blocks.BlockCursedEarth$EventHandler@2acccf94 spawnParticle(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 48: ASM: class com.rwtema.extrautils2.blocks.BlockTeleporter$EventHandler clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 49: ASM: com.rwtema.extrautils2.power.ClientPower@b8b6e65 playerPowerManagerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 50: ASM: com.rwtema.extrautils2.power.ClientPower@b8b6e65 clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 51: ASM: me.ichun.mods.ichunutil.common.module.worldportals.client.core.EventHandlerWorldPortalClient@34b600c1 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 52: ASM: me.ichun.mods.glass.client.core.EventHandlerClient@d372f89 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 53: ASM: me.ichun.mods.hats.client.core.EventHandlerClient@5f59e5de worldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 54: ASM: radixcore.core.RadixEvents@2ace07ba clientTickEventHandler(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 55: ASM: mca.core.forge.EventHooksFML@2e44294 clientTickEventHandler(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 56: ASM: romelo333.notenoughwands.proxy.ClientProxy@6c3bcef1 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 57: ASM: oreexcavation.handlers.EventHandler@7dfd1398 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 58: ASM: p455w0rdslib.handlers.ProcessHandlerClient@41fc0b2a onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 59: ASM: me.desht.pneumaticcraft.client.ClientTickHandler@497eb037 tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 60: ASM: me.desht.pneumaticcraft.client.AreaShowManager@31708666 tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 61: ASM: sereneseasons.handler.season.SeasonHandler@403f6039 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 62: ASM: com.tmtravlr.soundfilters.SoundTickHandler@69357e63 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 63: ASM: cofh.thermaldynamics.util.TickHandlerClient@7204195e tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 64: ASM: shadows.toaster.ToastControl@63c149c3 clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 65: ASM: weather2.EventHandlerFML@6d584d40 tickClient(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 66: ASM: net.montoyo.wd.client.ClientProxy@3740782b onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 67: ASM: p455w0rd.wct.init.ModEvents@5b73dd3b onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 68: ASM: cofh.thermaldynamics.duct.entity.TransportHandler@4a2e5db5 controlPlayer(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 69: ASM: com.creativemd.itemphysic.EventHandler@4b400549 gameTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 70: ASM: appeng.parts.PartPlacement@62b64bad playerInteract(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 71: ASM: class com.enderio.core.client.handlers.ClientHandler onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 72: ASM: com.enderio.core.common.util.Scheduler@2671fd1c onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 73: ASM: crazypants.enderio.base.init.CommonProxy$TickTimer@2dba22a1 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 74: ASM: pregenerator.impl.client.ClientHandler@627ab118 onClientTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 75: ASM: dan200.computality.shared.proxy.ComputerCraftProxyCommon$ForgeHandlers@3ba11d9 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 76: ASM: dan200.computality.client.proxy.ComputerCraftProxyClient$ForgeHandlers@36c58a97 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 77: ASM: li.cil.oc.common.EventHandler$@4a1fb13f onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 78: ASM: li.cil.oc.common.item.Tablet$@7335ed44 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 79: ASM: li.cil.oc.client.renderer.PetRenderer$@6530bdf6 tickStart(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 80: ASM: li.cil.oc.client.Sound$@7023c296 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 81: ASM: li.cil.oc.util.Audio$@44bad1b8 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 82: ASM: li.cil.oc.client.renderer.tileentity.HologramRenderer$@a60b3b8 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 83: ASM: li.cil.oc.client.renderer.TextBufferRenderCache$@2500c2be onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 84: ASM: mekanism.client.ClientTickHandler@5e3cecb9 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 85: ASM: pl.asie.computronics.tape.PortableDriveManager@5ae78c85 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 86: ASM: pl.asie.computronics.util.sound.Audio@18e28da6 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 87: ASM: flaxbeard.cyberware.common.handler.EssentialsMissingHandler@365d219e overlayPre(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 88: ASM: flaxbeard.cyberware.common.handler.CyberwareMenuHandler@5639b6e4 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 89: ASM: com.brandon3055.draconicevolution.client.handler.ClientEventHandler@2c5c62d7 tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 90: ASM: gigaherz.inventoryspam.ScrollingOverlay@2b02ac84 clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 91: ASM: p455w0rdslib.LibEvents@a61c8ec tickStart(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 92: ASM: me.desht.pneumaticcraft.common.semiblock.SemiBlockManager@4c00ac5e onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 93: ASM: com.kamesuta.mc.signpic.CoreHandler@3d64d9ce onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 94: ASM: cofh.thermaldynamics.render.RenderDuctItems@70af491c clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 95: ASM: class com.deflatedpickle.justthetips.events.ScreenHook onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 96: ASM: zmaster587.advancedRocketry.event.PlanetEventHandler@6ea2ba24 tickClient(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 97: ASM: forestry.core.TickHandlerCoreClient@733a9d8a onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 98: ASM: forestry.core.multiblock.MultiblockClientTickHandler@22b7ae90 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 99: ASM: codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler@5b0f4036 clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 100: ASM: codechicken.multipart.ControlKeyHandler$@71f9e569 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 101: ASM: journeymap.client.forge.event.StateTickHandler@2132ca1e onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 102: ASM: reborncore.common.multiblock.MultiblockClientTickHandler@5f91b159 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 103: ASM: mezz.jei.gui.GuiEventHandler@5cbeab8 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 104: ASM: com.rwtema.extrautils2.utils.MCTimer@119fd5c5 clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 105: ASM: appeng.hooks.TickHandler@611e08c5 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[09:34:19] [main/ERROR]: 106: ASM: com.creativemd.creativecore.event.CreativeTickHandler@306754bf onEventTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[09:34:19] [main/ERROR]: 107: ASM: net.montoyo.mcef.example.ExampleMod@23295627 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[09:34:19] [main/ERROR]: 108: LOW
[09:34:19] [main/ERROR]: 109: ASM: org.blockartistry.DynSurround.client.sound.SoundEngine@3b4f20fc clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 110: LOWEST
[09:34:19] [main/ERROR]: 111: ASM: class codechicken.lib.internal.CCLLog onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 112: ASM: noppes.npcs.client.ClientTickHandler@2a9ed9a8 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:19] [main/ERROR]: 113: ASM: DiagnosticHandler{name=Diagnostics} tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[09:34:33] [main/INFO]: World unloaded; killing screens...
[09:34:57] [Server thread/INFO]: Saving chunks for level 'New World'/ExtraUtils2_Quarry_Dim
[09:34:57] [Server thread/INFO]: Saving chunks for level 'New World'/Storage Cell
[09:35:48] [Server thread/INFO]: VoiceServer: Shutting down server...
[09:35:48] [Server thread/INFO]: Saving clock state for the next reload
[09:35:48] [MiniServClient/WARN]: Connection was closed, stopping...
[09:35:48] [Server thread/INFO]: Miniserv server stopped
[09:35:48] [Server thread/INFO]: Stopping server
[09:35:48] [Server thread/INFO]: Saving players
[09:35:48] [Server thread/INFO]: Saving worlds
[09:35:48] [Server thread/INFO]: Saving chunks for level 'New World'/overworld
[09:35:48] [Netty Local Client IO #0/INFO]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[09:35:49] [Server thread/INFO]: Saving chunks for level 'New World'/ExtraUtils2_Quarry_Dim
[09:35:49] [Server thread/INFO]: Saving chunks for level 'New World'/Storage Cell
[09:35:49] [Server thread/INFO]: World unloaded; killing screens...
[09:35:51] [Server thread/INFO]: World unloaded; killing screens...
[09:35:51] [Server thread/INFO]: World unloaded; killing screens...
[09:35:51] [Server thread/INFO]: Unloading dimension 0
[09:35:51] [Server thread/INFO]: Unloading dimension -9999
[09:35:51] [Server thread/INFO]: Unloading dimension 2
[09:40:44] [Server thread/INFO]: Applying holder lookups
[09:40:44] [Server thread/INFO]: Holder lookups applied
[09:40:44] [Server thread/INFO]: RFTools: server is stopping. Shutting down gracefully
```
</details>

**Comment by ErdbeerbaerLP** [comment]
Just found that line

at org.blockartistry.DynSurround.registry.season.SeasonInfoToughAsNails.getSeasonType

**Comment by Forstride** [comment]
You need to wait for Dynamic Surroundings to update and remove support for the old seasons in TAN.
