### ISSUE TITLE
Crash When Loading

### ISSUE THREAD

**Issue by QuadBoy** [Glitchfiend/ToughAsNails#595]
I had a crash when loading the game with
1.12.2-forge1.12.2-14.23.5.2768
AppleSkin-mc1.12-1.0.9.jar
Mantle-1.12-1.3.3.39.jar
natura-1.12.2-4.3.2.62.jar
ToughAsNails-1.12.2-3.1.0.132-universal.jar
VanillaFix-1.0.9-97.jar

VanillaFix gave me this crash report:
`
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2018-11-26 20:42:18 MST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tough As Nails (toughasnails)
Caused by: java.lang.NullPointerException
    at toughasnails.init.ModConfig.lambda$init$0(ModConfig.java:64)
    at toughasnails.init.ModConfig$$Lambda$166/379619701.apply(Unknown Source)
    at toughasnails.init.ModConfig.populateDataMap(ModConfig.java:92)
    at toughasnails.init.ModConfig.init(ModConfig.java:64)
    at toughasnails.core.ToughAsNails.init(ToughAsNails.java:83)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:534)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3929)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 418225816 bytes (398 MB) / 805306368 bytes (768 MB) up to 3221225472 bytes (3072 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2768 9 mods loaded, 9 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID           | Version         | Source                                      | Signature                                |
       |:----- |:------------ |:--------------- |:------------------------------------------- |:---------------------------------------- |
       | UCHI  | minecraft    | 1.12.2          | minecraft.jar                               | None                                     |
       | UCHI  | mcp          | 9.42            | minecraft.jar                               | None                                     |
       | UCHI  | FML          | 8.0.99.99       | forge-1.12.2-14.23.5.2768.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHI  | forge        | 14.23.5.2768    | forge-1.12.2-14.23.5.2768.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHI  | appleskin    | 1.0.9           | AppleSkin-mc1.12-1.0.9.jar                  | None                                     |
       | UCHI  | mantle       | 1.12-1.3.3.39   | Mantle-1.12-1.3.3.39.jar                    | None                                     |
       | UCHI  | natura       | 1.12.2-4.3.2.62 | natura-1.12.2-4.3.2.62.jar                  | None                                     |
       | UCHEE | toughasnails | 3.1.0.132       | ToughAsNails-1.12.2-3.1.0.132-universal.jar | None                                     |
       | UCH   | vanillafix   | 1.0.9-97        | VanillaFix-1.0.9-97.jar                     | None                                     |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
  GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 23.20.16.4973' Renderer: 'Intel(R) UHD Graphics 620'
  Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced)
                               - NaturaOverworld (Enabled/Not Forced)
                               - NaturaNether (Enabled/Not Forced)
                               - NaturaDecorative (Enabled/Not Forced)
                               - NaturaTools (Enabled/Not Forced)
                               - NaturaEntities (Enabled/Not Forced)
                               - NaturaOredict (Enabled/Forced)
                               - NaturaWorld (Enabled/Not Forced)
  Suspected Mods: Tough As Nails (toughasnails)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
  LWJGL: 2.9.4
  OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 23.20.16.4973, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz`

**Comment by Wabbit0101** [comment]
I had a similar error (snipped below). It seems to be caused when config files contain references to mod items that are not present. In my case I was rebuilding up a server modpack and I temporarily removed some mods; TAN promptly died on subsequent load when referring to some customization that used one of the mods' items. (File in question was the block_temperature.json config file.)

The culprit line might be: 

> tempData -> tempData.predicate.getBlock().getRegistryName().toString()

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tough As Nails (toughasnails)
Caused by: java.lang.NullPointerException
    at toughasnails.init.ModConfig.lambda$init$0(ModConfig.java:64)
    at toughasnails.init.ModConfig.populateDataMap(ModConfig.java:92)
    at toughasnails.init.ModConfig.init(ModConfig.java:64)
    at toughasnails.core.ToughAsNails.init(ToughAsNails.java:83)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
```
