### ISSUE TITLE
Issue with Roots

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/ToughAsNails#64]
Hello! Running a small collection of mods and when [Roots](http://minecraft.curseforge.com/projects/roots?gameCategorySlug=mc-mods&projectID=246183) was installed, I ran into this error. CPU throttles to 100% on world generation.

Unexpected error
java.lang.ClassCastException: elucent.roots.capability.RootsCapabilityManager$1ManaCapabilityProvider cannot be cast to toughasnails.temperature.TemperatureHandler
    at toughasnails.handler.temperature.TemperatureOverlayHandler.onPostRenderOverlay(TemperatureOverlayHandler.java:62)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_268_TemperatureOverlayHandler_onPostRenderOverlay_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159)
    at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:888)
    at net.minecraftforge.client.GuiIngameForge.renderHelmet(GuiIngameForge.java:268)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:133)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1369)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at toughasnails.handler.temperature.TemperatureOverlayHandler.onPostRenderOverlay(TemperatureOverlayHandler.java:62)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_268_TemperatureOverlayHandler_onPostRenderOverlay_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159)
    at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:888)
    at net.minecraftforge.client.GuiIngameForge.renderHelmet(GuiIngameForge.java:268)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:133)

**Comment by Forstride** [comment]
Why did you close this?  Did the author of the other mod fix it, or...?
