### ISSUE TITLE
server startup crash after updating to new version

### ISSUE THREAD

**Issue by LimeTheOn** [Glitchfiend/ToughAsNails#79]
```
[11:02:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World
[11:02:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[11:02:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[11:02:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[11:02:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     ... 13 more
[11:02:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer toughasnails.asm.transformer.WorldTransformer@dffa30b from coremod TANLoadingPlugin
[11:02:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234)
[11:02:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[11:02:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[11:02:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     ... 15 more
[11:02:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: Caused by: java.lang.RuntimeException: No method instruction node found matching aht getBiomeGenForCoords (Lcl;)Laig;
[11:02:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]:     at toughasnails.asm.ASMHelper.getUniqueMethodInsnNode(ASMHelper.java:63)
[11:02:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]:     at toughasnails.asm.transformer.WorldTransformer.transformWorld(WorldTransformer.java:133)
[11:02:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]:     at toughasnails.asm.transformer.WorldTransformer.transform(WorldTransformer.java:43)
[11:02:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]:     at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230)
[11:02:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]:     ... 17 more
```

**Comment by LimeTheOn** [comment]
nevermind it just fails to state that the mod was duplicated in the mods folder
