### ISSUE TITLE
Kick when i made a leaf armor

### ISSUE THREAD

**Issue by Gabm2K** [Glitchfiend/ToughAsNails#847]
### What's the issue you encountered?

The mod is installed client-side and server-side but it says "internal server error" when joining the server since i made a leaf armour

### How can the issue be reproduced?

The mit says "internal server error" when joining the server since i made a leaf armour

### Logs

[16:25:19] [Server thread/INFO]: _GabiX_[/127.0.0.1:49517] logged in with entity id 628 at (270.0697805648362, 63.0, 227.8153584627428) [16:25:19] [Server thread/INFO]: multiplayer.player.joined [16:25:20] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:49517 net.minecraft.class_148: Ticking player         at net.minecraft.class_3222.method_14226(class_3222.java:650) ~[server-intermediary.jar:?]         at net.minecraft.class_3244.method_18784(class_3244.java:267) ~[server-intermediary.jar:?]         at net.minecraft.class_2535.method_10754(class_2535.java:393) ~[server-intermediary.jar:?]         at net.minecraft.class_3242.method_14357(class_3242.java:176) ~[server-intermediary.jar:?]         at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1009) ~[server-intermediary.jar:?]         at net.minecraft.class_3176.method_3813(class_3176.java:294) ~[server-intermediary.jar:?]         at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:889) ~[server-intermediary.jar:?]         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:691) ~[server-intermediary.jar:?]         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275) ~[server-intermediary.jar:?]         at java.base/java.lang.Thread.run(Thread.java:1570) [?:?] Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_1163         at toughasnails.item.LeafArmorItem.method_7888(LeafArmorItem.java:28) ~[ToughAsNails-fabric-1.20.6-9.2.0.178.jar:?]         at net.minecraft.class_1799.method_7917(class_1799.java:642) ~[server-intermediary.jar:?]         at net.minecraft.class_1661.method_7381(class_1661.java:242) ~[server-intermediary.jar:?]         at net.minecraft.class_1657.method_6007(class_1657.java:590) ~[server-intermediary.jar:?]         at net.minecraft.class_1309.method_5773(class_1309.java:2529) ~[server-intermediary.jar:?]         at net.minecraft.class_1657.method_5773(class_1657.java:306) ~[server-intermediary.jar:?]         at net.minecraft.class_3222.method_14226(class_3222.java:586) ~[server-intermediary.jar:?]         ... 9 more Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1163         at toughasnails.item.LeafArmorItem.method_7888(LeafArmorItem.java:28) ~[ToughAsNails-fabric-1.20.6-9.2.0.178.jar:?]         at net.minecraft.class_1799.method_7917(class_1799.java:642) ~[server-intermediary.jar:?]         at net.minecraft.class_1661.method_7381(class_1661.java:242) ~[server-intermediary.jar:?]         at net.minecraft.class_1657.method_6007(class_1657.java:590) ~[server-intermediary.jar:?]         at net.minecraft.class_1309.method_5773(class_1309.java:2529) ~[server-intermediary.jar:?]         at net.minecraft.class_1657.method_5773(class_1657.java:306) ~[server-intermediary.jar:?]         at net.minecraft.class_3222.method_14226(class_3222.java:586) ~[server-intermediary.jar:?]         ... 9 more

### Mod Version

9.2.0.178

**Comment by Troyeer** [comment]
Same is happening to me.

**Comment by Troyeer** [comment]
> Same is happening to me.

[05.06 17:02:58] [Server] net.minecraft.class_Ticking player
[05.06 17:02:58] [Server] 	at net.minecraft.class_3222.method_14226(class_3222.java:650) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.class_3244.method_18784(class_3244.java:267) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.class_2535.method_10754(class_2535.java:393) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.class_3242.method_14357(class_3242.java:176) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1009) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.class_3176.method_3813(class_3176.java:294) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:889) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:691) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[05.06 17:02:58] [Server] Caused byjava.lang.NoClassDefFoundError: net/minecraft/class_1163
[05.06 17:02:58] [Server] 	at toughasnails.item.LeafArmorItem.method_7888(LeafArmorItem.java:28) ~[ToughAsNails-fabric-1.20.6-9.2.0.178.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.class_1799.method_7917(class_1799.java:642) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.class_1661.method_7381(class_1661.java:242) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.class_1657.method_6007(class_1657.java:590) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.class_1309.method_5773(class_1309.java:2529) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.class_1657.method_5773(class_1657.java:306) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.class_3222.method_14226(class_3222.java:586) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	... more
[05.06 17:02:58] [Server] Caused byjava.lang.ClassNotFoundException: net.minecraft.class_1163
[05.06 17:02:58] [Server] 	at toughasnails.item.LeafArmorItem.method_7888(LeafArmorItem.java:28) ~[ToughAsNails-fabric-1.20.6-9.2.0.178.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.class_1799.method_7917(class_1799.java:642) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.class_1661.method_7381(class_1661.java:242) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.class_1657.method_6007(class_1657.java:590) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.class_1309.method_5773(class_1309.java:2529) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.class_1657.method_5773(class_1657.java:306) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	at net.minecraft.class_3222.method_14226(class_3222.java:586) ~[server-intermediary.jar:?]
[05.06 17:02:58] [Server] 	... more
[05.06 17:02:58] [Disconnect] sexo has disconnected, reasonInternal server error
[05.06 17:02:58] [Server] [Server thread/INFO]: multiplayer.player.left

**Comment by CalCrafter24** [comment]
I had this problem before and made a post about it, but it got closed aswell

**Comment by CalCrafter24** [comment]
I managed to get it fixed, I just installed the newest version of the mod on both my side and the server (I had the same before, just not the newest version)
